-- AI Content Factory: additive production migration.
alter table public.content_jobs
  add column if not exists thumbnail_url text,
  add column if not exists thumbnail_prompt text,
  add column if not exists qa_status text,
  add column if not exists qa_report jsonb,
  add column if not exists queue_status text,
  add column if not exists attempt_count integer not null default 0,
  add column if not exists last_worker_at timestamptz,
  add column if not exists scheduled_at timestamptz;

create index if not exists content_jobs_queue_idx
  on public.content_jobs(queue_status, scheduled_at, updated_at desc);

create table if not exists public.analytics_snapshots (
  id bigint generated by default as identity primary key,
  captured_at timestamptz not null default now(),
  start_date date,
  end_date date,
  totals jsonb not null default '{}'::jsonb,
  top_videos jsonb not null default '[]'::jsonb
);
create index if not exists analytics_snapshots_captured_idx on public.analytics_snapshots(captured_at desc);
alter table public.analytics_snapshots enable row level security;
